# Generated by Django 3.2.9 on 2021-12-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211206_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
